<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
---
HOSTS:
  el7:
    roles:
      - default
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      # The TPM2 simulator RPMs are currently in the unstable repositories
      simp_unstable:
        baseurl: 'https://download.simp-project.com/simp/yum/unstable/simp6/el/$releasever/$basearch/simp/'
        gpgcheck: 0

  el8:
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>
    yum_repos:
      # The TPM2 simulator RPMs are currently in the unstable repositories
      simp_unstable:
        baseurl: 'https://download.simp-project.com/simp/yum/unstable/simp6/el/$releasever/$basearch/simp/'
        gpgcheck: 0

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 512
  synced_folder: enabled
  ssh:
    timeout: 2

<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
# vb_gui: true
